=== fastalme/msoft-dae-talleres/t00-soap/invoice-ws/src/main/resources/invoice/invoice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://dae.msoft.edu/ws/invoice"
           xmlns="http://dae.msoft.edu/ws/invoice"
           elementFormDefault="qualified">

    <xs:complexType name="invoiceDetailType">
        <xs:sequence>
            <xs:element type="xs:long" name="productId"/>
            <xs:element type="xs:string" name="productDescription"/>
            <xs:element type="xs:double" name="productPrice"/>
            <xs:element type="xs:long" name="count"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="invoiceType">
        <xs:sequence>
            <xs:element type="xs:string" name="invoiceId"/>
            <xs:element type="xs:dateTime" name="invoiceDate"/>
            <xs:element type="xs:long" name="customerId"/>
            <xs:element name="invoiceDetails">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element type="invoiceDetailType" name="invoiceDetail"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element type="xs:double" name="subtotal"/>
            <xs:element type="xs:double" name="tax15"/>
            <xs:element type="xs:double" name="total"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="invoice" type="invoiceType"/>

</xs:schema>

=== fastalme/msoft-dae-talleres/t00-soap/invoice-ws/src/main/resources/invoice/invoice.xml
<?xml version="1.0" encoding="UTF-8" ?>
<invoice xmlns="http://dae.msoft.edu/ws/invoice"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://dae.msoft.edu/ws/invoice invoice.xsd">
    <invoiceId>8c7801c6-bc6a-4dca-829b-248722594494</invoiceId>
    <invoiceDate>2024-09-07T06:42:29-05:00</invoiceDate>
    <customerId>1</customerId>
    <invoiceDetails>
        <invoiceDetail>
            <productId>101</productId>
            <productDescription>Ticket-ST</productDescription>
            <productPrice>200.00</productPrice>
            <count>1</count>
        </invoiceDetail>
        <invoiceDetail>
            <productId>102</productId>
            <productDescription>Ticket-PR</productDescription>
            <productPrice>350.00</productPrice>
            <count>2</count>
        </invoiceDetail>
    </invoiceDetails>
    <subtotal>900.00</subtotal>
    <tax15>135.00</tax15>
    <total>1035.00</total>
</invoice>
